// src/views/lottery/components/LotteryPrize.tsx
import { useEffect } from 'react'
import LotteryAction from './LotteryAction'
import lotteryConfig from '../core/lottery-config'
import { useLotteryVersion, notifyLotteryChange } from '../core/lottery-store'
import { transform } from '../3d/3d-animate'
import STATUS from '../3d/3d-status'
import { toast } from './feedback'
import { stopShowcase } from '../core/lottery-showcase'
import type { Prize } from '../core/lottery-types'
import './lottery-prize.scss'

async function selectPrize(prize: Prize) {
  stopShowcase()
  if (STATUS.isRun()) {
    toast('正在抽奖中，不能切换奖项！')
    return void 0
  }
  STATUS.setStatusRun()
  lotteryConfig.currentPrize = prize.id
  notifyLotteryChange()
  await transform('table', 1000) // TODO重复点击处理
  STATUS.setStatusWait()
}

export default function LotteryPrize() {
  useLotteryVersion() // 抽奖/切换奖项后剩余数量、进度条、选中态自动刷新
  const prizeList = lotteryConfig.prizeList
  // 选中态直接从全局配置派生：沿用已选奖项，否则默认最后一个（等级最低的奖项）
  const currentPrize = lotteryConfig.getCurrentPrize()
  const currentPrizeIndex = currentPrize
    ? prizeList.findIndex(_ => _.id === currentPrize.id)
    : prizeList.length - 1

  useEffect(() => {
    // 把默认选中同步回全局配置（渲染期不允许改外部状态，放到 effect 里）
    if (!lotteryConfig.currentPrize) {
      lotteryConfig.currentPrize = prizeList[prizeList.length - 1]['id']
      notifyLotteryChange()
    }
  }, [prizeList])

  return (
    <div className="prize-wrap">
      <ul className="prize-list">
        {prizeList.map((item, index) => (
          <li
            key={index}
            className={'prize-item' + (index === currentPrizeIndex ? ' shine' : '')}
            onClick={() => selectPrize(item)}
          >
            {item.img && (
              <div className="prize-item-left">
                <img src={item.img} alt={item.name} />
              </div>
            )}
            <div className="prize-item-right">
              <div className="prize-item-title">{item.name}</div>
              <div className="prize-item-count" style={{ display: 'none' }}>{item.count}名</div>
              <div className="prize-item-count-wrap">
                <div className="prize-item-count-text">{item.countRemain}/{item.count}</div>
                <div className="progress">
                  <div
                    style={{ width: (item.countRemain / item.count) * 100 + '%' }}
                    className="progress-bar progress-bar-danger progress-bar-striped active"
                  ></div>
                </div>
              </div>
            </div>
            <span className="line-1"></span>
            <span className="line-2"></span>
            <span className="line-3"></span>
            <span className="line-4"></span>
          </li>
        ))}
      </ul>
      <LotteryAction />
    </div>
  )
}

// src/views/lottery/lottery-prize.vue
<template>
  <div class="prize-wrap">
    <ul class="prize-list">
      <li class="prize-item"
          v-for="(item, index) in prizeList" :key="index"
          :class="{shine: index === currentPrizeIndex, done: index === donePrizeIndex}"
          @click="selectPrize(item, index)">
        <div class="prize-item-left" v-if="false">
          <img src="http://n1.itc.cn/img8/wb/recom/2016/03/02/145687903767748488.JPEG" alt="">
        </div>
        <div class="prize-item-right">
          <div class="prize-item-title">{{ item.name }}</div>
          <div class="prize-item-name" v-if="false">{{ item.detail }}</div>
          <div class="prize-item-count" style="display: none;">{{ item.count }}名</div>
          <div class="prize-item-count-wrap">
            <div class="prize-item-count-text">{{ item.countRemain }}/{{ item.count }}</div>
            <div class="progress">
              <div
                :style="{width: item.countRemain / item.count * 100 + '%'}"
                class="progress-bar progress-bar-danger progress-bar-striped active"
              ></div>
            </div>
          </div>
        </div>
        <span class="line-1"></span>
        <span class="line-2"></span>
        <span class="line-3"></span>
        <span class="line-4"></span>
      </li>
    </ul>
    <LotteryAction/>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import LotteryAction from './lottery-action.vue';
import lotteryConfig from './lottery-config';
import { transform } from './3d-animate';
import STATUS from './3d-status';
import type { Prize } from './lottery-types';

const prizeList = lotteryConfig.prizeList;
const currentPrizeIndex = ref<number | null>(null);
const donePrizeIndex = ref<number | null>(null);

async function selectPrize(prize: Prize, index: number) {
  if (STATUS.isRun()) {
    alert('正在抽奖中或者已经是当前奖项状态，不能切换奖项！');
    return void 0;
  }
  STATUS.setStatusRun();
  currentPrizeIndex.value = index;
  lotteryConfig.currentPrize = prize.id;
  await transform('table', 1000); // TODO重复点击处理
  STATUS.setStatusWait();
}

onMounted(() => {
  const currentPrize = lotteryConfig.getCurrentPrize()
  if (!currentPrize) {
    currentPrizeIndex.value = prizeList.length - 1;
    lotteryConfig.currentPrize = prizeList[prizeList.length - 1]['id'];
  } else {
    const index = lotteryConfig.prizeList.findIndex(_ => _.id === currentPrize.id);
    currentPrizeIndex.value = index;
  }
});
</script>

<style lang="scss" scoped>
@use './lottery-prize.scss';
</style>
